{
    trafficRegistrationPoints(
        searchQuery: {roadCategoryIds: [E, R, F, K, P], countyNumbers: [3], isOperational: true, trafficType: VEHICLE, registrationFrequency: CONTINUOUS}
        ) {
        id
        name
        location {
            coordinates {
                latLon {
                    lat
                    lon
                }
            }
            roadReference{
                shortForm
                roadCategory{
                    id
                }
            }
            roadLinkSequence{
                roadLinkSequenceId
                relativePosition
            }
            roadReferenceHistory{
                validFrom
                validTo
            }
            county{
                name
                number
                geographicNumber
            countryPart{
                id
                name
            }
            }
            municipality{
            name
            number
            }
        }
        trafficRegistrationType            
        dataTimeSpan {
            firstData
            firstDataWithQualityMetrics
            latestData {
                volumeByDay
                volumeByHour
                volumeAverageDailyByYear
                volumeAverageDailyBySeason
                volumeAverageDailyByMonth
            }
        }
    }
}
